spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  application:
    name: crawl_controller
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 10s
        health-check-path: /actuator/health
        default-query-tag: http
        prefer-ip-address: true
        register: true
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
