spring:
  application:
    name: item_db
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        health-check-interval: 10s
        health-check-path: /actuator/health
        # Optional: Configure how the gateway discovers services
        default-query-tag: http
        prefer-ip-address: true
        register: true
        enabled: true
  datasource:
    url: jdbc:h2:file:./data/items
    username: sa
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: items
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
server:
  port: 8008

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always