server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: crawl_controller
          uri: http://crawlcontroller:8086
          predicates:
            - Path=/crawl_controller/api/crawl/**
            - Method=POST
          filters:
            - StripPrefix=1
        - id: user_params
          uri: lb://userparameters
          predicates:
            - Path=/user_params/api/user/**
            - Method=POST
          filters:
            - StripPrefix=1
        - id: item_db
          uri: http://itemdb:8008
          predicates:
            - Path=/item_db/api/item/**
            - Method=POST, GET
          filters:
            - StripPrefix=1
        - id: menu_db
          uri: http://menudb:8066
          predicates:
            - Path=/menu_db/api/plan/**
            - Method=GET
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 10s
        health-check-path: /actuator/health
        default-query-tag: http
        prefer-ip-address: true
        register: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always